### ISSUE TITLE
buildDateToChangesetCache breaks past 6/9

### ISSUE THREAD

**Issue by monicachew** [monicachew/pinning-dashboard#10]
GET http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2014-06-11-mozilla-central-debug/firefox-32.0a1.en-US.debug-linux-i686.txt 404 (Not Found) chartoptions.js:30
XMLHttpRequest cannot load http://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/2014-06-11-mozilla-central-debug/firefox-32.0a1.en-US.debug-linux-i686.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://people.mozilla.org' is therefore not allowed access.

**Comment by monicachew** [comment]
D'oh @mozkeeler, 6/9 is the merge date, these should be 33 instead of 32.

**Comment by mozkeeler** [comment]
fixed by #11
