### ISSUE TITLE
move people.mozilla.org/~mchew/pinning_dashboard somewhere else

### ISSUE THREAD

**Issue by monicachew** [monicachew/pinning-dashboard#27]
I wonder if github pages supports this...

@mozkeeler This is not really time sensitive since you can always pull from the repo, but the link from https://wiki.mozilla.org/SecurityEngineering/Public_Key_Pinning should be updated as well. I think that's the only reference.

**Comment by mozkeeler** [comment]
I pulled the most recent master to http://people.mozilla.org/~dkeeler/pinning-dashboard/ and updated the wiki. As discussed, we can put this somewhere more permanent later, but I think this is fine for now.

**Comment by monicachew** [comment]
Thanks!
